# Generated by Django 5.0.7 on 2024-11-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('project_type', models.CharField(choices=[('Pool Construction', 'Pool Construction'), ('Liner Install/Replacement', 'Liner Install/Replacement'), ('Home Renovation', 'Home Renovation'), ('Landscape Design', 'Landscape Design'), ('General Construction', 'General Construction'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Quotes',
        ),
    ]
