# Generated by Django 5.0.7 on 2024-11-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0006_quoterequest_delete_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
