# Generated by Django 5.0.7 on 2024-11-09 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0008_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='email',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
